// @ts-check

import { IoTimeSharp } from 'react-icons/io5';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  guideSidebar: [
    // 1. Shorthand: a bare string means {type: 'doc', id: 'intro'}
    'intro',

    // 2. Full form - label different from the page title
    {
      type: 'doc',
      id: 'installation',
      label: '⚡ Start here'
    },

    // 3. Section heading, with arbitraty HTML
    {
      type: 'html',
      value:
        '<div class="sidebar-section-title">Guides</div>',
        defaultStyle: false,
    },

    // 4. Category with an auto-generated index page
    {
      type: 'category',
      label: 'Configuration',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Configuration guides',
        description: 'Everything you can adjust in Nimbus',
        slug: '/category/configuration',
      },
      // Picks up every file in the folder, ordered by sidebar_position
      items: [{type: 'autogenerated', dirName: 'configuration'}],
    },

    // 5. Visual separator
    {
      type: 'html',
      value: '<hr style="margin:0.75rem 1rem; opacity:0.2;" />',
      defaultStyle: false,
    },

  ],

  referenceSidebar: [
    'syntax-reference',

    {
      type: 'category',
      label: 'Frequently asked questions',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'faq'}],
    },

    // 6. External link - gets the "leaves the site" icon automatically
    {
      type: 'link',
      label: 'Docusaurus docs',
      href: 'https://docusaurus.io/docs',
    },
  ],
};

export default sidebars;
